<?php
'[{ 
    "PSComputerName" : "DESKTOP-3S7B382", 
            "__GENUS" : "2", 
            "__CLASS" : "Win32_SystemEnclosure", 
            "__SUPERCLASS" : "CIM_Chassis", 
            "__PROPERTY_COUNT" : "37", 
            "__SERVER" : "DESKTOP-3S7B382", 
            "__NAMESPACE" : "root#cimv2", 
            "AudibleAlarm" : "", 
            "BreachDescription" : "", 
            "CableManagementStrategy" : "", 
            "Caption" : "Compartimento do Sistema", 
            "ChassisTypes" : "System.UInt16[]", 
            "CreationClassName" : "Win32_SystemEnclosure", 
            "CurrentRequiredOrProduced" : "", 
            "Depth" : "", 
            "Description" : "Compartimento do Sistema", 
            "HeatGeneration" : "", 
            "Height" : "", 
            "HotSwappable" : "", 
            "InstallDate" : "", 
            "LockPresent" : "False", 
            "Manufacturer" : "LENOVO", 
            "Model" : "", 
            "Name" : "Compartimento do Sistema", 
            "NumberOfPowerCords" : "", 
            "OtherIdentifyingInfo" : "", 
            "PartNumber" : "", 
            "PoweredOn" : "", 
            "Removable" : "", 
            "Replaceable" : "", 
            "SecurityBreach" : "", 
            "SecurityStatus" : "3", 
            "SerialNumber" : "PE03Y6UT", 
            "ServiceDescriptions" : "", 
            "ServicePhilosophy" : "", 
            "SKU" : "", 
            "SMBIOSAssetTag" : "NO Asset Tag", 
            "Status" : "", 
            "Tag" : "System Enclosure 0", 
            "TypeDescriptions" : "", 
            "Version" : "Lenovo ideapad 330-15IKB", 
            "VisibleAlarm" : "", 
            "Weight" : "", 
            "Width" : "", 
            "Scope" : "System.Management.ManagementScope", 
            "Path" : "\\DESKTOP-3S7B382\root\cimv2:Win32_SystemEnclosure.Tag="System Enclosure 0"", 
            "Options" : "System.Management.ObjectGetOptions", 
            "ClassPath" : "\\DESKTOP-3S7B382\root\cimv2:Win32_SystemEnclosure", 
            "Properties" : "System.Management.PropertyDataCollection", 
            "SystemProperties" : "System.Management.PropertyDataCollection", 
            "Qualifiers" : "System.Management.QualifierDataCollection", 
            "Site" : "", 
            "Container" : "" }]';
print_r($teste);

?>